---
- name: Configure firewall for InspIRCd
  copy: src=inspircd.rules dest=/etc/iptables.d/
  notify:
  - iptables
- name: Copy InspIRCd build artifacts
  copy: src=inspircd dest=/opt/
  notify:
  - inspircd
- name: Configure InspIRCd
  template: src={{ item }} dest=/opt/inspircd/conf/{{ item }} owner=root group=irc mode=0640
  with_items:
  - inspircd.conf
  - links.conf
  - modules.conf
  - opers.conf
  notify:
  - inspircd
- name: Copy SSL key and cert
  copy: src=secret/inspircd_{{ item }} dest=/opt/inspircd/conf/{{ item }} owner=root group=irc mode=0640
  with_items:
  - cert.pem
  - key.pem
  notify:
  - inspircd
- name: Make data directory
  file: path=/opt/inspircd/data state=directory owner=irc group=irc mode=0640
- name: Add InspIRCd init script
  copy: src=service dest=/etc/init.d/inspircd
- name: Start InspIRCd
  service: name=inspircd state=started enabled=yes
