---
- name: Set hostname
  template: src=hostname.j2 dest=/etc/hostname owner=root group=root mode=0644
  notify:
  - hostname
- name: Configure networking
  template: src=interfaces.j2 dest=/etc/network/interfaces owner=root group=root mode=0644
  notify:
  - networking
- name: Configure resolv.conf
  copy: src=resolv.conf dest=/etc/resolv.conf owner=root group=root mode=0644
- name: Add iptables script
  copy: src=iptables dest=/etc/network/if-up.d/iptables owner=root group=root mode=0755
- name: Make iptables.d
  file: path=/etc/iptables.d state=directory owner=root group=root mode=0755
- name: Configure IPv4 firewall
  copy: src=0common.rules dest=/etc/iptables.d/0common.rules owner=root group=root mode=0644
  notify:
  - iptables
- name: Configure IPv6 firewall
  copy: src=ip6tables.conf dest=/etc/ip6tables.conf owner=root group=root mode=0644
  notify:
  - iptables
- name: Remove motd
  file: path=/etc/motd state=absent
- name: Set apt sources
  copy: src=sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
- name: Install ntpd packages
  apt: pkg=ntp state=present update_cache=yes
- name: Configure ntpd
  copy: src=ntp.conf dest=/etc/ntp.conf
  notify:
  -  ntp
